version: "3"
services:
  node:
    build: .
    environment:
      - NEXT_JS_URL=http://localhost:3000
      - PUBLIC_URL=http://localhost:3000
    volumes:
      - "../:/workspace"
      - node_deps:/workspace/node_modules/
      - yarn_cache:/workspace/.yarn/cache/
    command: sleep infinity
volumes:
  node_deps:
  yarn_cache:
